name: Sync with Upstream

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync Upstream
        run: |
          git remote add upstream https://github.com/pages-cms/pages-cms.git || true
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
